import './globals.css';
import { Inter } from 'next/font/google';
import Navbar from './components/Navbar';
import Link from 'next/link';
import Script from 'next/script';
import AdBanner from './components/AdBanner';

const inter = Inter({ subsets: ['latin'], display: 'swap' });

export const metadata = {
  metadataBase: new URL('https://smartcalctools.xyz'),
  title: {
    default: 'SmartCalcTools — Halal Financial Calculators & Secure Developer Tools',
    template: '%s | SmartCalcTools',
  },
  description: '100% free, private, and client-side tools. Explore our Zakat Calculator, Murabaha Financing Calculator, Islamic FIRE tool, JSON Formatter, and secure WebGPU ChatPDF.',
  keywords: ['Islamic finance calculators', 'Zakat calculator', 'Murabaha calculator', 'Mudarabah profit calculator', 'Halal investment tools', 'JSON formatter', 'JWT decoder offline', 'client-side ChatPDF', 'free developer tools'],
  openGraph: {
    title: 'SmartCalcTools — Halal Financial Calculators & Secure Developer Tools',
    description: 'Free, offline-first developer tools and Sharia-compliant financial calculators. Private and secure.',
    url: 'https://smartcalctools.xyz',
    siteName: 'SmartCalcTools',
    type: 'website',
    locale: 'en_US',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'SmartCalcTools — Halal Finance & Pro Dev Tools',
    description: 'Explore our Zakat Calculator, Islamic FIRE tool, and ultra-secure offline developer utilities.',
  },
  robots: { index: true, follow: true },
  alternates: { canonical: 'https://smartcalctools.xyz' },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <Script 
          async 
          src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-2077857887750518" 
          crossOrigin="anonymous" 
          strategy="afterInteractive" 
        />
      </head>
      <body className={inter.className}>
        <Navbar />
        <main style={{ minHeight: 'calc(100vh - 200px)' }}>
          <AdBanner dataAdSlot="top-banner" />
          {children}
          <AdBanner dataAdSlot="bottom-banner" />
        </main>
        <footer className="footer">
          <div className="container">
            <div style={{ display: 'flex', gap: '24px', justifyContent: 'center', marginBottom: '16px', flexWrap: 'wrap' }}>
              <Link href="/about" style={{ color: 'var(--text-muted)' }}>About Us</Link>
              <Link href="/privacy-policy" style={{ color: 'var(--text-muted)' }}>Privacy Policy</Link>
              <Link href="/terms-of-service" style={{ color: 'var(--text-muted)' }}>Terms of Service & Disclaimer</Link>
              <Link href="/contact" style={{ color: 'var(--text-muted)' }}>Contact</Link>
            </div>
            
            {/* AdSense Required Disclaimer for E-E-A-T */}
            <div className="footer-disclaimer" style={{ maxWidth: '800px', margin: '0 auto 20px', fontSize: '0.85rem', color: 'var(--text-muted)', lineHeight: '1.6', textAlign: 'center' }}>
              <strong>Disclaimer:</strong> The calculators and tools on SmartCalcTools are provided for educational and mathematical estimation purposes only. The outputs generated by this site do not constitute a <em>Fatwa</em> (religious ruling), personalized Shariah advisory, or legal/financial advice. Please consult with a qualified Islamic scholar or your local Shariah board before making binding financial decisions.
            </div>

            <p>© 2026 SmartCalcTools. Free tools built for speed, privacy, and ethics.</p>
          </div>
        </footer>
      </body>
    </html>
  );
}
