export const metadata = {
  title: 'Terms of Service | SmartCalcTools',
  description: 'Terms and conditions for using SmartCalcTools.',
};

export default function TermsOfServicePage() {
  return (
    <div className="container" style={{ padding: '40px 20px', maxWidth: '800px', lineHeight: '1.8' }}>
      <h1>Terms of Service</h1>
      <p style={{ color: 'var(--text-muted)', marginBottom: '24px' }}>Last updated: June 2026</p>

      <section className="card" style={{ marginBottom: '32px' }}>
        <h2>1. Acceptance of Terms</h2>
        <p>
          By accessing and using SmartCalcTools, you accept and agree to be bound by the terms and provisions of this agreement.
        </p>
      </section>

      <section className="card" style={{ marginBottom: '32px' }}>
        <h2>2. Educational & Informational Purpose Only</h2>
        <p>
          The tools provided on this website, including but not limited to the Islamic Finance Calculators (Zakat, Murabaha, Mudarabah, Islamic FIRE), are for educational and informational purposes only.
        </p>
        <p style={{ marginTop: '12px' }}>
          <strong>No Financial or Religious Advice:</strong> We are not certified financial planners, nor are we Islamic scholars (Muftis). The results generated by our calculators are mathematical approximations based on general guidelines (e.g., AAOIFI standards). You must consult a qualified scholar or financial advisor before making actual financial decisions.
        </p>
      </section>

      <section className="card" style={{ marginBottom: '32px' }}>
        <h2>3. 'As Is' Service</h2>
        <p>
          Our services are provided "as is" without warranty of any kind, either express or implied, including without limitation warranties of merchantability, fitness for a particular purpose, or non-infringement. We are not liable for any calculation errors or direct/indirect damages arising from the use of our tools.
        </p>
      </section>
    </div>
  );
}
